export const progressData = [
  {
    title: "제목1",
    member: "만두",
    Mypercentage: 10,
    members: [
      { name: "만두1", percentage: 10 },
      { name: "예슬1", percentage: 20 },
      { name: "예레나1", percentage: 30 },
      { name: "기정1", percentage: 40 },
      { name: "곰달1", percentage: 50 },
      { name: "지노1", percentage: 100 },
    ],
  },
  {
    title: "제목2",
    member: "예슬",
    Mypercentage: 30,
    members: [
      { name: "만두", percentage: 50 },
      { name: "예슬", percentage: 40 },
      { name: "예레나", percentage: 30 },
      { name: "기정", percentage: 20 },
      { name: "곰달", percentage: 10 },
      { name: "지노", percentage: 0 },
    ],
  },
];

export const BeforeStartData = [
  {
    title: "시작 전1",
    content: "설명설명설명설명설명설명설명설명설명설명설명설명설명설명",
    category: "시사",
    tags: ["#최대4글", "자넘어가", "면잘리게"],
    startDate: "2022-07-11",
    schedule: "1주일에 2회",
    members: 4,
    waiting: 1,
  },
  {
    title: "시작 전2",
    content: "설명설명설명설명설명설명설명설명설명설명설명설명설명설명",
    category: "운동",
    tags: ["#최대4글", "자넘어가", "면잘리게"],
    startDate: "2022-07-10",
    schedule: "1주일에 2회",
    members: 2,
    waiting: 2,
  },
  {
    title: "시작 전3",
    content: "설명설명설명설명설명설명설명설명설명설명설명설명설명설명",
    category: "예술",
    tags: ["#최대4글", "자넘어가", "면잘리게"],
    startDate: "2022-07-07",
    schedule: "1주일에 2회",
    members: 3,
    waiting: 2,
  },
  {
    title: "시작 전4",
    content: "설명설명설명설명설명설명설명설명설명설명설명설명설명설명",
    category: "공부",
    tags: ["#최대4글", "자넘어가", "면잘리게"],
    startDate: "2022-07-15",
    schedule: "1주일에 2회",
    members: 5,
    waiting: 1,
  },
  {
    title: "시작 전5",
    content: "설명설명설명설명설명설명설명설명설명설명설명설명설명설명",
    category: "독서",
    tags: ["#최대4글", "자넘어가", "면잘리게"],
    startDate: "2022-07-23",
    schedule: "1주일에 2회",
    members: 1,
    waiting: 4,
  },
];

export const RecruitData = [
  {
    title: "모집1",
    content: "설명설명설명설명설명설명설명설명설명설명설명설명설명설명",
    startDate: "2022-07-10",
    schedule: "1주일에 2회",
    members: 1,
    waiting: 3,
  },
  {
    title: "모집2",
    content: "설명설명설명설명설명설명설명설명설명설명설명설명설명설명",
    startDate: "2022-07-10",
    schedule: "2주일에 5회",
    members: 4,
    waiting: 1,
  },
  {
    title: "모집3",
    content: "설명설명설명설명설명설명설명설명설명설명설명설명설명설명",
    startDate: "2022-07-21",
    schedule: "1주일에 4회",
    members: 3,
    waiting: 2,
  },
  {
    title: "모집4",
    content: "설명설명설명설명설명설명설명설명설명설명설명설명설명설명",
    startDate: "2022-07-16",
    schedule: "1주일에 3회",
    members: 5,
    waiting: 1,
  },
];

export const RequestData = [
  {
    title: "신청1",
    content: "설명설명설명설명설명설명설명설명설명설명설명설명설명설명",
    approve: false,
    tags: ["#최대4글", "자넘어가", "면잘리게"],
    startDate: "2022-08-01",
    schedule: "1주일에 2회",
    members: 4,
  },
  {
    title: "신청1",
    content: "설명설명설명설명설명설명설명설명설명설명설명설명설명설명",
    approve: true,
    tags: ["#최대4글", "자넘어가", "면잘리게"],
    startDate: "2022-08-04",
    schedule: "1주일에 2회",
    members: 2,
  },
  {
    title: "신청3",
    content: "설명설명설명설명설명설명설명설명설명설명설명설명설명설명",
    approve: false,
    tags: ["#최대4글", "자넘어가", "면잘리게"],
    startDate: "2022-08-07",
    schedule: "1주일에 2회",
    members: 3,
  },
  {
    title: "신청4",
    content: "설명설명설명설명설명설명설명설명설명설명설명설명설명설명",
    approve: true,
    tags: ["#최대4글", "자넘어가", "면잘리게"],
    startDate: "2022-09-01",
    schedule: "1주일에 2회",
    members: 5,
  },
  {
    title: "신청5",
    content: "설명설명설명설명설명설명설명설명설명설명설명설명설명설명",
    approve: false,
    tags: ["#최대4글", "자넘어가", "면잘리게"],
    startDate: "2022-10-23",
    schedule: "1주일에 2회",
    members: 1,
  },
];
