export const ChallengeData = [
  [
    {
      title: "제목",
      category: "시사1",
      tags: ["#최대4글", "자넘어가", "면잘리게"],
      date: "6월 15일",
      schedule: "1주일에 2회",
      members: 4,
    },
    {
      title: "제목",
      category: "시사2",
      tags: ["#최대4글", "자넘어가", "면잘리게"],
      date: "6월 15일",
      schedule: "1주일에 2회",
      members: 5,
    },
  ],
  [
    {
      title: "제목",
      category: "독서1",
      tags: ["#최대4글", "자넘어가", "면잘리게"],
      date: "6월 15일",
      schedule: "1주일에 2회",
      members: 3,
    },
    {
      title: "제목",
      category: "독서2",
      tags: ["#최대4글", "자넘어가", "면잘리게"],
      date: "6월 15일",
      schedule: "1주일에 2회",
      members: 5,
    },
  ],
  [
    {
      title: "제목",
      category: "외국어1",
      tags: ["#최대4글", "자넘어가", "면잘리게"],
      date: "6월 15일",
      schedule: "1주일에 2회",
      members: 1,
    },
    {
      title: "제목",
      category: "외국어2",
      tags: ["#최대4글", "자넘어가", "면잘리게"],
      date: "6월 15일",
      schedule: "1주일에 2회",
      members: 6,
    },
  ],
  [
    {
      title: "제목",
      category: "전공 기초1",
      tags: ["#최대4글", "자넘어가", "면잘리게"],
      date: "6월 15일",
      schedule: "1주일에 2회",
      members: 5,
    },
    {
      title: "제목",
      category: "전공 기초2",
      tags: ["#최대4글", "자넘어가", "면잘리게"],
      date: "6월 15일",
      schedule: "1주일에 2회",
      members: 4,
    },
  ],
  [
    {
      title: "제목",
      category: "예술1",
      tags: ["#최대4글", "자넘어가", "면잘리게"],
      date: "6월 15일",
      schedule: "1주일에 2회",
      members: 3,
    },
    {
      title: "제목",
      category: "예술 2",
      tags: ["#최대4글", "자넘어가", "면잘리게"],
      date: "6월 15일",
      schedule: "1주일에 2회",
      members: 1,
    },
  ],
  [
    {
      title: "제목",
      category: "습관1",
      tags: ["#최대4글", "자넘어가", "면잘리게"],
      date: "6월 15일",
      schedule: "1주일에 2회",
      members: 0,
    },
    {
      title: "제목",
      category: "습관2",
      tags: ["#최대4글", "자넘어가", "면잘리게"],
      date: "6월 15일",
      schedule: "1주일에 2회",
      members: 6,
    },
  ],
  [
    {
      title: "제목",
      category: "운동1",
      tags: ["#최대4글", "자넘어가", "면잘리게"],
      date: "6월 15일",
      schedule: "1주일에 2회",
      members: 4,
    },
    {
      title: "제목",
      category: "운동2",
      tags: ["#최대4글", "자넘어가", "면잘리게"],
      date: "6월 15일",
      schedule: "1주일에 2회",
      members: 2,
    },
  ],
  [
    {
      title: "제목",
      category: "기타1",
      tags: ["#최대4글", "자넘어가", "면잘리게"],
      date: "6월 15일",
      schedule: "1주일에 2회",
      members: 5,
    },
    {
      title: "제목",
      category: "기타2",
      tags: ["#최대4글", "자넘어가", "면잘리게"],
      date: "6월 15일",
      schedule: "1주일에 2회",
      members: 1,
    },
  ],
];
