export const ChallengeData = [
  [
    {
      title: "제목",
      category: "시사",
      tags: ["#최대4글", "자넘어가", "면잘리게"],
      date: "6월 15일",
      schedule: "1주일에 2회",
      members: 4,
    },
    {
      title: "제목2",
      category: "시사",
      tags: ["#최대4글", "자넘어가", "면잘리게"],
      date: "6월 15일",
      schedule: "1주일에 2회",
      members: 5,
    },
    {
      title: "제목3",
      category: "시사",
      tags: ["#최대4글", "자넘어가", "면잘리게"],
      date: "6월 15일",
      schedule: "1주일에 2회",
      members: 5,
    },
  ],
  [
    {
      title: "제목1",
      category: "독서",
      tags: ["#최대4글", "자넘어가", "면잘리게"],
      date: "6월 15일",
      schedule: "1주일에 2회",
      members: 3,
    },
    {
      title: "제목2",
      category: "독서",
      tags: ["#최대4글", "자넘어가", "면잘리게"],
      date: "6월 15일",
      schedule: "1주일에 2회",
      members: 5,
    },
  ],
  [
    {
      title: "제목1",
      category: "외국어",
      tags: ["#최대4글", "자넘어가", "면잘리게"],
      date: "6월 15일",
      schedule: "1주일에 2회",
      members: 1,
    },
    {
      title: "제목2",
      category: "외국어",
      tags: ["#최대4글", "자넘어가", "면잘리게"],
      date: "6월 15일",
      schedule: "1주일에 2회",
      members: 6,
    },
  ],
  [
    {
      title: "제목1",
      category: "전공 기초",
      tags: ["#최대4글", "자넘어가", "면잘리게"],
      date: "6월 15일",
      schedule: "1주일에 2회",
      members: 5,
    },
    {
      title: "제목2",
      category: "전공 기초",
      tags: ["#최대4글", "자넘어가", "면잘리게"],
      date: "6월 15일",
      schedule: "1주일에 2회",
      members: 4,
    },
  ],
  [
    {
      title: "제목1",
      category: "예술",
      tags: ["#최대4글", "자넘어가", "면잘리게"],
      date: "6월 15일",
      schedule: "1주일에 2회",
      members: 3,
    },
    {
      title: "제목2",
      category: "예술",
      tags: ["#최대4글", "자넘어가", "면잘리게"],
      date: "6월 15일",
      schedule: "1주일에 2회",
      members: 1,
    },
  ],
  [
    {
      title: "제목1",
      category: "습관",
      tags: ["#최대4글", "자넘어가", "면잘리게"],
      date: "6월 15일",
      schedule: "1주일에 2회",
      members: 0,
    },
    {
      title: "제목2",
      category: "습관",
      tags: ["#최대4글", "자넘어가", "면잘리게"],
      date: "6월 15일",
      schedule: "1주일에 2회",
      members: 6,
    },
  ],
  [
    {
      title: "제목1",
      category: "운동",
      tags: ["#최대4글", "자넘어가", "면잘리게"],
      date: "6월 15일",
      schedule: "1주일에 2회",
      members: 4,
    },
    {
      title: "제목2",
      category: "운동",
      tags: ["#최대4글", "자넘어가", "면잘리게"],
      date: "6월 15일",
      schedule: "1주일에 2회",
      members: 2,
    },
  ],
  [
    {
      title: "제목1",
      category: "기타",
      tags: ["#최대4글", "자넘어가", "면잘리게"],
      date: "6월 15일",
      schedule: "1주일에 2회",
      members: 5,
    },
    {
      title: "제목2",
      category: "기타",
      tags: ["#최대4글", "자넘어가", "면잘리게"],
      date: "6월 15일",
      schedule: "1주일에 2회",
      members: 1,
    },
  ],
];
